# The title shown on the component page
title: <%= componentName %>
# Label shown on index pages
label: <%= componentName %>
status: alpha
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: <%= componentType %>
  # custom-values: passed as {{custom-values}}
